### ISSUE TITLE
Make Audacium 100% offline only.

### ISSUE THREAD

**Issue by majestrate** [SartoxOnlyGNU/audacium#10]
**Is your feature request related to a problem? Please describe.**
Audacium is an audio editor, it has no reason to talk to the internet.

**Describe the solution you'd like**
We should gutt all networking related code.

**Describe alternatives you've considered**
Possibly include AppArmour profiles that disallow network access.

**Additional context**
[another fork](https://github.com/Sneeds-Feed-and-Seed/sneedacity/pull/69/files) seems to have done this but we can't cherry pick the commits as they decided to do a bulk rename of all the files.

I have time to work on this today.

**Comment by AnErrupTion** [comment]
I've already removed crash reporting, and disabled most update checking. I think there should only be checking for updates when Audacity starts and not periodically. This is what most other programs do, so what do you think?

**Comment by matt-hu** [comment]
I can see your point, however there is one use of it connecting to the internet I can see, checking for updates. This could be opt in, and could be useful when a package manager isn't being used (eg windows users)

**Comment by majestrate** [comment]
> I've already removed crash reporting, and disabled most update checking. I think there should only be checking for updates when Audacity starts and not periodically. This is what most other programs do, so what do you think?

on platforms where updates are not managed by a package manager it does make sense to keep it.
perhaps an AppArmour profile would be better here.

**Comment by AnErrupTion** [comment]
All update checking is going to be made to the GitHub repo, so I don't think there's much concern here.

**Comment by majestrate** [comment]
> All update checking is going to be made to the GitHub repo, so I don't think there's much concern here.

fair point.

**Comment by guss77** [comment]
It is probably a good idea to have a way for distribution packagers to disable update checks - these do not play well with package managers.
