### ISSUE TITLE
Matrix Room Link Invalid

### ISSUE THREAD

**Issue by ApoorvaKashyap** [SartoxOnlyGNU/audacium#11]
I'm unable to join the Matrix Room of this project. Element returns a msg saying that the room is invalid. Pls update the link if there has been a change or remove it if it is no longer being used.

**Comment by AnErrupTion** [comment]
Here it is: #audacium:envs.net (I made another one, since the other got deleted)

**Comment by ApoorvaKashyap** [comment]
Thanks. Pls update it in the readme as well.
