### ISSUE TITLE
Update Logo

### ISSUE THREAD

**Issue by matt-hu** [SartoxOnlyGNU/audacium#13]
I noticed the very nice logo on the readme, but it's yet to be integrated into the application. What are you intending to use for the app logo? The two option I could think of is the whole logo or just the headphones?

Just some suggestions.

**Comment by AnErrupTion** [comment]
I'm currently integrating it into the application, and properly scaling it (there's also a logo with only the headphones too which is going to be in the app) but currently I'm struggling so yeah x)

**Comment by matt-hu** [comment]
Ah ok good luck!

There seems to be lots of variants to deal with. Have you got any plans for more general re theming for the rest of the app going forwards?

**Comment by AnErrupTion** [comment]
I'm going to add the dark theme from DarkAudacity and plan to make the UI more organized.

**Comment by matt-hu** [comment]
Just had a little look and there is already, but it's not automatically activated by the OS theme. Not sure how to do this but might be something I can look into. The main thing for me is in my opinion some of the buttons etc are looking a little dated.

**Comment by AnErrupTion** [comment]
I know there's already a dark theme but it's not finished, the one from DA much better. It'll probably be the default theme in Audacium.

**Comment by matt-hu** [comment]
Ah ok. Good idea with dark as default!
