### ISSUE TITLE
The links for downloading, wiki and forums don't work

### ISSUE THREAD

**Issue by Lilith-In-Starlight** [SartoxOnlyGNU/audacium#2]
https://audacium.seb1g.live/download, https://audacium.seb1g.live/forum and https://audacium.seb1g.live/wiki aren't functional. They all lead to a 404 page:

![image](https://user-images.githubusercontent.com/56773311/124504365-f0338400-dd8c-11eb-9755-98863fac5645.png)

**Comment by AnErrupTion** [comment]
Yeah, they haven't been done yet. Are you looking to download the latest build?

**Comment by Lilith-In-Starlight** [comment]
Yeah, where could I do so?

**Comment by AnErrupTion** [comment]
I could build one and upload it in releases.

**Comment by Lilith-In-Starlight** [comment]
That would be great, yeah

**Comment by AnErrupTion** [comment]
Alright, I uploaded the latest build!

**Comment by Lilith-In-Starlight** [comment]
Very appreciated!
