### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by matt-hu** [SartoxOnlyGNU/audacium#20]
We are going to need user documentation of some sorts. Now, the problem is the official Audacity documentation is on GitHub, however *it uses a creative commons license*. This means, as far as I am aware, if we use it we have to leave their copy-write notice in.

Now the other thing is how to host it. By the looks of it it is currently hosted on one of their servers, a luxury I'm assuming we don't have. So, here of the things I could think of:
- Use the wiki
- Use GitHub Pages (with markdown)
- Use ReadTheDocs

There may be much better solutions, these are just ones I've used in the past.

**Comment by AnErrupTion** [comment]
I think we're going to use the GH wiki.

**Comment by matt-hu** [comment]
Ah ok. The only thing with this approach is people can't PR changes to the wiki, but I guess that's not too much of a problem.

**Comment by AnErrupTion** [comment]
They can edit the wiki though.

**Comment by matt-hu** [comment]
At the moment we can't. It must be set to maintainers only or something?

**Comment by AnErrupTion** [comment]
I mean they can edit pages of the wiki.

**Comment by matt-hu** [comment]
Yeah I meant that only maintainers can edit the wiki. So if I wanted to help and add some stuff, for example, I couldn't. I'm guessing that is intentional though

**Comment by AnErrupTion** [comment]
Anyone could also open an issue to tell a problem with the wiki. Closing as we know what we'll do.
