### ISSUE TITLE
GNU/Linux build

### ISSUE THREAD

**Issue by charliemartinez** [SartoxOnlyGNU/audacium#21]
Hello! Could you make a self-sufficient build for GNU / Linux (that works, for example, inside the / opt folder). Something similar to what they did for Windows, only for GNU / Linux. 

If you releases that build, I promise to package it in .deb and incorporate it into the official repository of the distro that I maintain (Quirinux GNU / Linux). 

Greetings

:-)

Charlie Martínez

**Comment by matt-hu** [comment]
I think that audacity use AppImages for their releases, but a .deb would be nice to have.

**Comment by AnErrupTion** [comment]
I really don't see what you mean. Do you mean a CI integration that automatically makes builds? Do you mean a build that can install itself to /opt?

**Comment by charliemartinez** [comment]
> I think that audacity use AppImages for their releases, but a .deb would be nice to have.

Of course, what I do is unpack the appimages that do not have official deb and then repackage them in deb. Example: Storyboarder. I think if you guys can launch an Audacium AppImage, it could do that. My debs are "installed" in the / opt folder even though they are actually portable, due to the nature of their origin.

**Comment by charliemartinez** [comment]
> I really don't see what you mean. Do you mean a CI integration that automatically makes builds? Do you mean a build that can install itself to /opt?

A portable build for GNU / Linux.

**Comment by matt-hu** [comment]
Yeah ok, we are working on getting the appimage working

**Comment by AnErrupTion** [comment]
Linux builds are now available, closing issue.

**Comment by charliemartinez** [comment]
> Linux builds are now available, closing issue.

Thank you !!!

**Comment by charliemartinez** [comment]
> Linux builds are now available, closing issue.

Sorry, do you mean [this unofficial installer](https://github.com/ApoorvaKashyap/audacium/releases/tag/Audacium-Deb-July-22)? Because I couldn't find an official one for GNU/Linux.
