### ISSUE TITLE
Please accept me as an contributor/maintainer of the repo

### ISSUE THREAD

**Issue by awslabspl** [SartoxOnlyGNU/audacium#22]
Ive been using Audacity ever since, I know it inside out, and do care a lot for it.

**Comment by AnErrupTion** [comment]
Do you know how to develop in C and/or C++?

**Comment by awslabspl** [comment]
> Do you know how to develop in C and/or C++?
Of course I know :)

**Comment by AnErrupTion** [comment]
Do you have any projects that you can show me?

**Comment by awslabspl** [comment]
> Do you have any projects that you can show me?

Sure........ just take a look [at my profile page](https://github.com/awslabspl?tab=repositories) some 80% projects are public..........

**Comment by AnErrupTion** [comment]
All your projects do not have any C/C++ code in it.

**Comment by awslabspl** [comment]
> All your projects do not have any C/C++ code in it.

It doesnt mean I dont know/Im not familiar with C/C++..........

**Comment by realseb1g** [comment]
We'll consider it bro

**Comment by AnErrupTion** [comment]
After thinking I may accept you if you can do some pull requests on the project (in the code, so that I can prove you know C and/or C++) and if I see that you do know those languages I'll invite you into the organization.

**Comment by xlaustin1** [comment]
Hi

**Comment by fossdd** [comment]
@AnErrupTion You may also want to look at the tenacity chat log: https://github.com/tenacityteam/tenacity/discussions/159#discussioncomment-980104

**Comment by AnErrupTion** [comment]
I did look at those, but if he isn't toxic with me and my team members and contributors, it's fine.

**Comment by AnErrupTion** [comment]
Closing this issue because @awslabspl has agreed to do PRs. Waiting for them! :D
