### ISSUE TITLE
OS X Version - prebuilt binary?

### ISSUE THREAD

**Issue by kirkmarkarian** [SartoxOnlyGNU/audacium#29]
Couldn't find one, and am not a programmer.  How soon?  I'd prefer not to go back to the pre-trouble version of Audacity.

**Comment by AnErrupTion** [comment]
Go to the Actions tab of the project, click on the latest workflow that has a checkmark on a green background, and go to the bottom and you should find a macOS build.

**Comment by kirkmarkarian** [comment]
No luck - I found it, but it won't open, not even if I go to the "Wrapper" on the inside of the file.
![Screen Shot 2021-07-10 at 6 51 59 AM](https://user-images.githubusercontent.com/38725630/125165344-66e4ce80-e14b-11eb-8eb3-6b2b02bca7d2.png)
![Screen Shot 2021-07-10 at 6 51 55 AM](https://user-images.githubusercontent.com/38725630/125165345-677d6500-e14b-11eb-9b08-55a417d2cc6d.png)
![Screen Shot 2021-07-10 at 6 51 41 AM](https://user-images.githubusercontent.com/38725630/125165347-6815fb80-e14b-11eb-8893-37d411993e10.png)
![Screen Shot 2021-07-10 at 6 51 11 AM](https://user-images.githubusercontent.com/38725630/125165349-68ae9200-e14b-11eb-9788-a8b47289ed08.png)
![Screen Shot 2021-07-10 at 6 51 03 AM](https://user-images.githubusercontent.com/38725630/125165350-68ae9200-e14b-11eb-9324-6a8506fffa5c.png)

**Comment by realseb1g** [comment]
We don't have any macOS users here to test, I recommend coming to our Discord or Matrix and you can be our tester
