### ISSUE TITLE
Additional library required to build on Linux.

### ISSUE THREAD

**Issue by CHJ85** [SartoxOnlyGNU/audacium#35]
Hi there. I wanted to try the latest version, so I decided to build on Linux.
However, the 2 pa_jack_dynload files are missing.

```
CMake Error at cmake-proxies/portaudio-v19/CMakeLists.txt:2 (add_library):
  Cannot find source file:

    /home/chris/Downloads/audacium/lib-src/portaudio-v19/src/hostapi/jack/pa_jack_dynload.c

CMake Error at cmake-proxies/portaudio-v19/CMakeLists.txt:2 (add_library):
  No SOURCES given to target: portaudio-v19

CMake Generate step failed.  Build files cannot be regenerated correctly.

```
The files you need are https://github.com/audacity/audacity/blob/master/lib-src/portaudio-v19/src/hostapi/jack/pa_jack_dynload.c and https://github.com/audacity/audacity/blob/master/lib-src/portaudio-v19/src/hostapi/jack/pa_jack_dynload.h

After I added those and built it again, it worked fine.
Also if it's not too much trouble, could you include Linux and Mac in your releases?

**Comment by AnErrupTion** [comment]
Alright I'll add those files. Also, for the Linux and Mac builds, you can find them in the Actions tab. The reason I can't put them into my releases is because I don't have any Mac hardware and my current PC can't really support VMs.
