### ISSUE TITLE
Contributor

### ISSUE THREAD

**Issue by SnowmanKing** [SartoxOnlyGNU/audacium#37]
Hello, I could be a contributor if you need another one. Thanks

**Comment by AnErrupTion** [comment]
Sure. Do you have experience in C/C++, and do you have any projects that you can show me?

**Comment by SnowmanKing** [comment]
To be honest, I don't have a lot of experience. I could help with the wiki or in minor areas in the code. I haven't uploaded any projects to github (most were in python).

**Comment by AnErrupTion** [comment]
Well, there are tons of python files in Audacity, and if you could rewrite some of the files to wiki pages it would be nice! If you want to start with the wiki I'd have to make you part of the organization (so that you can edit it), but if you're going to start with the python stuff you could just do PRs. What will you do?

**Comment by SnowmanKing** [comment]
I can start with the wiki and then see about working on the python later. Do we want to make it similar to the audacity wiki (of course with obvious changes).

**Comment by Camology** [comment]
Can be closed now, from the official page:

_Donations

You can donate to me via PayPal using the Sponsor button on GitHub and going to my Liberapay page, or support me via Bitcoin or Monero :

Bitcoin : bc1qz6f2gu8f2vr8knyt8y76jxc8h7an93695kyyj0
Monero : 4834cgrEKBgbYVugTxHzZPJqyDXBBhreNF4CxauZCbLAQfrzeFuRifE4Pwy6uAH3t61rLwe89XF3v775qfuRzr8mRHzuZfk_

**Comment by AnErrupTion** [comment]
@Camology What does this have to do with the current issue topic?

**Comment by SnowmanKing** [comment]
@Camology What are you talking about?

**Comment by Camology** [comment]
wrong issue, my mistake

**Comment by AnErrupTion** [comment]
@SnowmanKing I've invited you into the organization (you have to accept). I'm trusting you since you've been since the start of the project. One major fuck up (like any intentional security flaw, for example...) and you're out.
