### ISSUE TITLE
Stop promoting Discord use

### ISSUE THREAD

**Issue by EchedeyLR** [SartoxOnlyGNU/audacium#4]
Last times I have seen some FLOSS projects go in this way for discussions.

There are FLOSS replacements to it, which you already use, and are very easy to use.

I understand that how the thing are done, the bridge is not going to be closed.

What I would do:
- Stop linking to Discord and accepting new users on it.
- Create a Matrix Space for the development.
- Close the bridge and the Discord community when all the users migrate to Matrix or leave it.

**Comment by realseb1g** [comment]
Agreed
