### ISSUE TITLE
Failing to enable plugins

### ISSUE THREAD

**Issue by MissLav** [SartoxOnlyGNU/audacium#6]
**Failing to enable plugins**

**To Reproduce**
1. Go to 'the Effects Tab'
2. Click on 'add / remove plugin'
3. Select all 
4. click enable 
5. click ok
6. goto effects tab 
7. see that none of the plugins got applied 
**Expected behavior**

OS: Manjaro 
Build:  AUR repo 

Video Showing issue
https://cdn.discordapp.com/attachments/492169001858760704/861977860297195571/2021-07-06_09-23-32.mp4

**Comment by AnErrupTion** [comment]
What version?

**Comment by nulldg** [comment]
I'm getting the same issue. It seems other forks are having this problem too.

**Comment by MissLav** [comment]
![image](https://user-images.githubusercontent.com/51702517/124626310-12e99980-de6e-11eb-8cb7-dfbc47f5ec8c.png)


> What version?

hope this helps

**Comment by AnErrupTion** [comment]
This is probably an Audacity bug too as I haven't touched with plugins at all. I'll try to see what's going on though.

**Comment by brmonaghan** [comment]
Error: Failed to load shared library '.dll' (error 126: The specified module could not be found.)
Same here.

**Comment by CHJ85** [comment]
> This is probably an Audacity bug too as I haven't touched with plugins at all. I'll try to see what's going on though.
So you're saying the forkers should all role back a version?
According to the Audacity forums, this error message seems to be ffmpeg related. I tried to create a dummy file for avformat-55.dll, but with no luck.
The program is basically trying to find the Windows version of ffmpeg.

**Comment by AnErrupTion** [comment]
Audacium compiles with FFmpeg already though, it's weird..
@MissLav what happens if you enable all plugins, click ok then just restart the app instead of going to check the plugins again?

**Comment by brmonaghan** [comment]
It doesn’t work.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by AnErrupTion** [comment]
> Error: Failed to load shared library '.dll' (error 126: The specified module could not be found.)
> Same here.

Also how does this happen?

**Comment by brmonaghan** [comment]
I enabled the plugins and it did not show under audacity effects.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by AnErrupTion** [comment]
Well it also does the same thing on Windows, just tested.

**Comment by majestrate** [comment]
if there was a big name change it could be that when a shared library is loaded it's looking for a symbol with `audacity` in it.

**Comment by nulldg** [comment]
This exact bug seems to affect other forks too. Whatever this fork changed didn't cause it. I suspect it's an issue with 3.0.3 or with the release build missing something important.

**Comment by AnErrupTion** [comment]
Yeah, probably Audacity fucked up something. I'll try to track where this issue is coming from first.

**Comment by majestrate** [comment]
is there a known working tag that can be bisected against?

**Comment by haya3218** [comment]
Heard this has been fixed in Sneeds-Feed-and-Seed/sneedacity#66. Prolly merge or smth?
