### ISSUE TITLE
Remove Audacity Branding from Localisations

### ISSUE THREAD

**Issue by ApoorvaKashyap** [SartoxOnlyGNU/audacium#9]
The localisation files of this project reference Audacity's name several times. Since the name of the project has changed, this should be updated as well to avoid confusion.

**Comment by AnErrupTion** [comment]
I don't see what you mean by localisation files.

**Comment by ApoorvaKashyap** [comment]
Check the locale folder. I think it contains the various translations of the Audacity Interface.

**Comment by ApoorvaKashyap** [comment]
I'm willing to update those files if you want to go ahead.

**Comment by AnErrupTion** [comment]
Sure! You can make a PR!

**Comment by AnErrupTion** [comment]
And yeah I didn't notice those files, how dumb of me x)

**Comment by ApoorvaKashyap** [comment]
Fine. I'll update them and make a PR in a 2-3 days.

**Comment by AnErrupTion** [comment]
Alright, thanks for contributing to the project!

**Comment by InfosecGurung** [comment]
I'm working on this issue, but only modifying the comments and not code. I would not like to break the code :)

**Comment by AnErrupTion** [comment]
The PR didn't fix this issue, so I'm re-opening it.

**Comment by AnErrupTion** [comment]
How is the translation going @ApoorvaKashyap?

**Comment by ApoorvaKashyap** [comment]
It is just taking a little longer than I anticipated. I'm still working on it.

**Comment by InfosecGurung** [comment]
I'll resume working on this issue, but won't be able to change all the occurances since there are a lot of files.

**Comment by InfosecGurung** [comment]
Some of the files have been edited, not all. Will be sending PRs for the same. This should be over withing a week or two. Kindly do not close this issue since it's not been fixed. Thank you :D

I've been only lightly editing the files (only comments).
